
logging:
    level: 
        '[org.hibernate.stat]': debug

    # Log Patterns
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'

spring:
    #DEVTOOLS
    devtools:
        add-properties: true
    # Database
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/authserverdb
        username: alfser
        password: sistemas@mttpocos

    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
        
myoauth2:
    auth: 
        provider-uri-issuer: "http://127.0.0.1:8080"